version: '3'
services:
  caster-db:
    image: mysql:5.7
    volumes:
      - ./local-database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: casters
      MYSQL_USER: niall
      MYSQL_PASSWORD: local
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  caster-be:
    ports:
      - 8081:8080
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dev
    depends_on:
      - caster-db

